export const events = [
  {
    image: "/images/event1.png",
    title: "React Summit Amsterdam",
    slug: "react-summit-amsterdam",
    location: "Amsterdam, Netherlands",
    date: "June 12, 2026",
    time: "9:00 AM",
  },
  {
    image: "/images/event2.png",
    title: "Next.js Conf",
    slug: "nextjs-conf",
    location: "San Francisco, CA",
    date: "October 15, 2026",
    time: "10:00 AM",
  },
  {
    image: "/images/event3.png",
    title: "JSNation Live",
    slug: "jsnation-live",
    location: "New York, NY",
    date: "July 8, 2026",
    time: "8:30 AM",
  },
  {
    image: "/images/event4.png",
    title: "Cloud Native Computing Meetup",
    slug: "cloud-native-computing-meetup",
    location: "London, UK",
    date: "August 21, 2026",
    time: "6:00 PM",
  },
  {
    image: "/images/event5.png",
    title: "AI Builders Hackathon",
    slug: "ai-builders-hackathon",
    location: "Austin, TX",
    date: "September 5, 2026",
    time: "9:00 AM",
  },
  {
    image: "/images/event6.png",
    title: "TypeScript Community Day",
    slug: "typescript-community-day",
    location: "Berlin, Germany",
    date: "November 3, 2026",
    time: "9:30 AM",
  },
];
